# Generated by Django 5.2.3 on 2025-06-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=1, max_length=150, unique=True, verbose_name="Никнейм"
            ),
            preserve_default=False,
        ),
    ]
