# Generated by Django 5.2.3 on 2025-06-27 09:58

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Создаем группы
    manager_group, _ = Group.objects.get_or_create(name="Managers")
    user_group, _ = Group.objects.get_or_create(name="Users")

    # Получаем ContentType для модели User
    user_content_type = ContentType.objects.get_for_model(
        Group
    )  # Используем Group как proxy

    # Создаем и назначаем права
    can_view_all, _ = Permission.objects.get_or_create(
        codename="can_view_all",
        name="Can view all objects",
        content_type=user_content_type,
    )
    can_block_users, _ = Permission.objects.get_or_create(
        codename="can_block_users",
        name="Can block users",
        content_type=user_content_type,
    )
    can_disable_mailings, _ = Permission.objects.get_or_create(
        codename="can_disable_mailings",
        name="Can disable mailings",
        content_type=user_content_type,
    )

    # Назначаем права группам
    manager_group.permissions.add(can_view_all, can_block_users, can_disable_mailings)


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
