# Generated by Django 5.2.3 on 2025-07-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_alter_client_owner_alter_mailing_owner"),
        ("mailings", "0004_auto_20250703_2319"),
    ]

    operations = []
